# Generated by Django 3.2.6 on 2021-08-26 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0002_auto_20210826_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetup',
            name='participants',
            field=models.ManyToManyField(blank=True, null=True, related_name='participant', to='meetups.Participant'),
        ),
    ]
